<a href="https://colab.research.google.com/github/4060E027/AI-2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 34.25 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [4]:
ls

examples/  sample_data/


In [5]:
cd examples/

/content/examples


In [6]:
ls

AUTHORS     CONTRIBUTING.md  LICENSE    setup.py
CODEOWNERS  courses/         lite/      templates/
community/  __init__.py      README.md  tensorflow_examples/


In [7]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

In [8]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [9]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [12]:
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.20592408, -0.1148669 , -0.02120852],
       [ 0.48232512,  0.24310827,  0.42627418]])

In [20]:
data = np.random.uniform(1, 5, 10)
data

array([2.66516352, 1.55757886, 1.95657357, 1.63583229, 2.3542152 ,
       4.73483753, 2.63872347, 3.09510568, 4.87955864, 4.74760398])

In [21]:
sum(data)

30.26519273512983

In [22]:
data.shape

(10,)

In [23]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [28]:
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [35]:
np.linspace(1., 4., 12) # start, end, num

array([1.        , 1.27272727, 1.54545455, 1.81818182, 2.09090909,
       2.36363636, 2.63636364, 2.90909091, 3.18181818, 3.45454545,
       3.72727273, 4.        ])

In [36]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [37]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

使用ENDPOINT就會把最後面的數去掉，如:3就會成為2.9

In [38]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [41]:
np.linspace(2.0, 3.0, num=6, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8, 3. ]), 0.2)

顯示間格數

In [40]:
np.linspace(2.0, 3.0, num=5, retstep=False)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [42]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [43]:
np.indices((3, 4))

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [45]:
np.indices((4, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [46]:
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [47]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [48]:
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [53]:
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [57]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [59]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

2次陣列2次複製