<a href="https://colab.research.google.com/github/4060E027/AI-2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 34.25 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [4]:
ls

examples/  sample_data/


In [5]:
cd examples/

/content/examples


In [6]:
ls

AUTHORS     CONTRIBUTING.md  LICENSE    setup.py
CODEOWNERS  courses/         lite/      templates/
community/  __init__.py      README.md  tensorflow_examples/


In [7]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

In [8]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [9]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [12]:
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.20592408, -0.1148669 , -0.02120852],
       [ 0.48232512,  0.24310827,  0.42627418]])

In [20]:
data = np.random.uniform(1, 5, 10)
data

array([2.66516352, 1.55757886, 1.95657357, 1.63583229, 2.3542152 ,
       4.73483753, 2.63872347, 3.09510568, 4.87955864, 4.74760398])

In [21]:
sum(data)

30.26519273512983